name: Flywheel — PR
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
jobs:
  conduct:
    uses: point-source/flywheel/.github/workflows/pr.yml@__FLYWHEEL_VERSION__
    with:
      app-id: ${{ vars.FLYWHEEL_GH_APP_ID }}
    secrets:
      app-private-key: ${{ secrets.FLYWHEEL_GH_APP_PRIVATE_KEY }}
