name: Flywheel — Push
on:
  push:
    branches: ["**"]
jobs:
  release:
    uses: point-source/flywheel/.github/workflows/push.yml@__FLYWHEEL_VERSION__
    with:
      app-id: ${{ vars.FLYWHEEL_GH_APP_ID }}
      flywheel-ref: __FLYWHEEL_VERSION__
    secrets:
      app-private-key: ${{ secrets.FLYWHEEL_GH_APP_PRIVATE_KEY }}
