#!/usr/bin/env bash
# scripts/governance-lint.sh
#
# Lints the symphonize governance files (SPEC.md, ROADMAP.md, REQUIREMENTS.md,
# README.md) and validates their structure. Single source of truth shared by a
# local run and the Governance Lint CI workflow
# (.github/workflows/governance-lint.yml), so local and CI results are identical.
#
# This is a vendored adaptation of symphonize's stock reusable governance-lint
# workflow (repentsinner/symphonize@v0). We vendor rather than `uses:` it for
# one reason: its CHANGELOG.md structure check requires a Keep-a-Changelog
# layout (an `## [Unreleased]` section and `## [N.N.N]` headings), which is
# fundamentally incompatible with the CHANGELOG.md flywheel ships — that file is
# generated by semantic-release, whose headings carry compare-links and
# prerelease suffixes (`## [1.2.4-dev.1](…compare…) (date)`) and never an
# Unreleased section. semantic-release owns CHANGELOG.md and regenerates it on
# every release, so the file cannot be hand-edited to satisfy the check. The
# reusable workflow exposes no input to disable that one step, so we run every
# other v0 check here and simply omit it. (fuse_tools landed the same opt-out;
# revisit if upstream adds a path/step exclusion or cuts a release without the
# CHANGELOG check.)
#
# Vale (prose linting) is run by the vale-action step in governance-lint.yml
# under CI (it also posts the inline PR annotations); this script runs vale only
# when invoked locally, deferring to the action under GitHub Actions to avoid a
# double-run.
#
# Usage: ./scripts/governance-lint.sh

set -euo pipefail

# Pin markdownlint-cli2 to the version the markdownlint-cli2-action@v19 step
# resolved before this was vendored, so a rule's verdict can't drift between a
# local run and CI.
MDL_VERSION="0.17.2"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# README heading profile — flywheel is an application, not a library.
README_TYPE="application"

# Tree-wide discovery, excluding the git internals. flywheel's docs/ tree uses
# lowercase filenames (docs/design/spec.md, docs/design/requirements.md) that do
# not match the case-sensitive governance names below, so no extra exclude is
# needed to keep it out of the governed set.
FIND_EXCLUDES=(-not -path './.git/*')

errors=0

# ── markdownlint ─────────────────────────────────────────────────────────────
if ! command -v npx >/dev/null 2>&1; then
  echo -e "${RED}✗ npx (Node.js) is required for governance markdownlint but was not found.${NC}"
  exit 1
fi

# Globs match the reusable workflow's; .markdownlint-cli2.jsonc supplies the
# rule config and the CHANGELOG.md ignore.
echo "Running markdownlint-cli2@${MDL_VERSION}..."
if ! npx --yes "markdownlint-cli2@${MDL_VERSION}" \
  "**/SPEC.md" "**/ROADMAP.md" "**/README.md" "**/REQUIREMENTS.md"; then
  errors=$((errors + 1))
fi

# ── Vale (prose linting) ─────────────────────────────────────────────────────
# Under GitHub Actions the vale-action step owns prose linting (and PR
# annotations); locally we run vale directly so a local lint matches CI.
if [ -f .vale.ini ]; then
  if command -v vale >/dev/null 2>&1; then
    echo "Running vale (prose lint)..."
    if ! vale .; then
      errors=$((errors + 1))
    fi
  elif [ -z "${GITHUB_ACTIONS:-}" ]; then
    echo -e "${RED}✗ vale is required for governance prose linting but was not found.${NC}"
    echo "  Install it to match CI: https://github.com/vale-cli/vale/releases"
    exit 1
  fi
fi

# ── SPEC.md status lines ─────────────────────────────────────────────────────
while IFS= read -r specfile; do
  echo "Checking status lines in $specfile"
  section=""
  expect_status=false
  while IFS= read -r line; do
    if [[ "$line" =~ ^##\ [^#] ]]; then
      if $expect_status; then
        echo "::error file=${specfile}::Section '$section' has no *Status: line"
        errors=$((errors + 1))
      fi
      section="$line"
      expect_status=true
      continue
    fi
    if $expect_status; then
      [[ -z "$line" ]] && continue
      if [[ "$line" =~ ^\*Status:\ (not\ started|in\ progress|complete)\*$ ]]; then
        expect_status=false
      else
        echo "::error file=${specfile}::Section '$section' has invalid or missing status line: $line"
        errors=$((errors + 1))
        expect_status=false
      fi
    fi
  done < <(tr -d '\r' < "$specfile")
  if $expect_status; then
    echo "::error file=${specfile}::Section '$section' has no *Status: line (end of file)"
    errors=$((errors + 1))
  fi
done < <(find . -name 'SPEC.md' "${FIND_EXCLUDES[@]}" | sort)

# ── README.md headings ───────────────────────────────────────────────────────
if [ -f README.md ]; then
  headings=$(grep -E '^## ' README.md | sed 's/^## //' | tr '[:upper:]' '[:lower:]')
  check_heading() {
    local label="$1" pattern="$2"
    if ! echo "$headings" | grep -qxE "$pattern"; then
      echo "::error::README.md missing required heading: $label (expected pattern: $pattern)"
      errors=$((errors + 1))
    fi
  }
  check_heading "License" "licen(se|sing)|licensing note"
  case "$README_TYPE" in
    application)
      check_heading "Getting Started" "quick start|getting started|install(ation)?"
      check_heading "Usage" "usage"
      ;;
  esac
else
  echo "::error::README.md not found"
  errors=$((errors + 1))
fi

# ── Heading slug formats ─────────────────────────────────────────────────────
while IFS= read -r specfile; do
  while IFS= read -r line; do
    echo "$line" | grep -qE '§spec:[a-z0-9-]+' || {
      echo "::error file=${specfile}::Heading missing §spec: slug: $line"; errors=$((errors + 1)); }
  done < <(grep -E '^## ' "$specfile" | tr -d '\r')
done < <(find . -name 'SPEC.md' "${FIND_EXCLUDES[@]}" | sort)

while IFS= read -r roadmapfile; do
  while IFS= read -r line; do
    echo "$line" | grep -qE '^### §road:[a-z0-9-]+' || {
      echo "::error file=${roadmapfile}::Heading missing §road: slug pattern: $line"; errors=$((errors + 1)); }
  done < <(grep -E '^### ' "$roadmapfile" | tr -d '\r')
done < <(find . -name 'ROADMAP.md' "${FIND_EXCLUDES[@]}" | sort)

while IFS= read -r reqfile; do
  while IFS= read -r line; do
    echo "$line" | grep -qE '§req:[a-z0-9-]+' || {
      echo "::error file=${reqfile}::Heading missing §req: slug: $line"; errors=$((errors + 1)); }
  done < <(grep -E '^## ' "$reqfile" | tr -d '\r')
done < <(find . -name 'REQUIREMENTS.md' "${FIND_EXCLUDES[@]}" | sort)

# ── Cross-document references ────────────────────────────────────────────────
slugs_file=$(mktemp)
trap 'rm -f "$slugs_file"' EXIT

while IFS= read -r f; do grep -E '^## ' "$f" | grep -oE '§spec:[a-z0-9-]+' >> "$slugs_file" || true; done \
  < <(find . -name 'SPEC.md' "${FIND_EXCLUDES[@]}")
while IFS= read -r f; do grep -E '^### ' "$f" | grep -oE '§road:[a-z0-9-]+' >> "$slugs_file" || true; done \
  < <(find . -name 'ROADMAP.md' "${FIND_EXCLUDES[@]}")
while IFS= read -r f; do grep -E '^## ' "$f" | grep -oE '§req:[a-z0-9-]+' >> "$slugs_file" || true; done \
  < <(find . -name 'REQUIREMENTS.md' "${FIND_EXCLUDES[@]}")

while IFS= read -r govfile; do
  lineno=0
  in_fenced_block=false
  while IFS= read -r line; do
    lineno=$((lineno + 1))
    if echo "$line" | grep -qE '^```'; then
      if $in_fenced_block; then in_fenced_block=false; else in_fenced_block=true; fi
      continue
    fi
    $in_fenced_block && continue
    # Strip inline code spans before scanning for §refs (sed per-span, not a
    # greedy bash expansion).
    # shellcheck disable=SC2001
    stripped=$(echo "$line" | sed 's/`[^`]*`//g')
    refs=$(echo "$stripped" | grep -oE '§(spec|req|road):[a-z0-9-]+' || true)
    [ -z "$refs" ] && continue
    for ref in $refs; do
      prefix="${ref%%:*}"; prefix="${prefix#§}"
      basename=$(basename "$govfile")
      case "$prefix" in
        spec) [ "$basename" = "SPEC.md" ] && echo "$line" | grep -q '^## ' && continue ;;
        road) [ "$basename" = "ROADMAP.md" ] && echo "$line" | grep -q '^### ' && continue ;;
        req)  [ "$basename" = "REQUIREMENTS.md" ] && echo "$line" | grep -q '^## ' && continue ;;
      esac
      grep -qxF "$ref" "$slugs_file" || {
        echo "::error file=${govfile},line=${lineno}::Dangling reference ${ref} — no matching heading found"
        errors=$((errors + 1)); }
    done
  done < <(tr -d '\r' < "$govfile")
done < <(find . \( -name 'SPEC.md' -o -name 'ROADMAP.md' -o -name 'REQUIREMENTS.md' \) "${FIND_EXCLUDES[@]}" | sort)

# ── Result ───────────────────────────────────────────────────────────────────
if [ "$errors" -gt 0 ]; then
  echo -e "${RED}✗ Governance lint failed (${errors} check group(s) with errors)${NC}"
  exit 1
fi
echo -e "${GREEN}✓ Governance lint passed${NC}"
